apiVersion: apps/v1
kind: Deployment
metadata:
  name: phab-discord-hook
spec:
  revisionHistoryLimit: 2
  replicas: 1
  selector:
    matchLabels:
      app: phab-discord-hook
  template:
    metadata:
      labels:
        app: phab-discord-hook
    spec:
      containers:
        - name: phab-discord-hook
          image: docker.pkg.github.com/modcastpodcast/phab-discord-hook/app
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
          - name: phids-to-discord
            mountPath: /phids.json
          envFrom:
            - secretRef:
                name: phab-discord-hook
      volumes:
        - name: phids-to-discord
          configMap:
            name: phids-to-discord
                        
---
apiVersion: v1
kind: Service
metadata:
  name: phab-discord-hook
spec:
  selector:
    app: phab-discord-hook
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
